fix

diff --git a/package/network/services/dropbear/files/dropbear.init b/package/network/services/dropbear/files/dropbear.init
--- a/package/network/services/dropbear/files/dropbear.init
+++ b/package/network/services/dropbear/files/dropbear.init
@@ -7,19 +7,16 @@ STOP=50
 
 USE_PROCD=1
 PROG=/usr/sbin/dropbear
-NAME=dropbear
 PIDCOUNT=0
 
-extra_command "killclients" "Kill ${NAME} processes except servers and yourself"
+extra_command "killclients" "Kill dropbear processes except servers and yourself"
 
-_dropbearkey()
-{
+_dropbearkey() {
 	/usr/bin/dropbearkey "$@" 0<&- 1>&- 2>&-
 }
 
 # $1 - host key file name
-hk_verify()
-{
+hk_verify() {
 	[ -f "$1" ] || return 1
 	[ -s "$1" ] || return 2
 	_dropbearkey -y -f "$1" || return 3
@@ -27,41 +24,47 @@ hk_verify()
 }
 
 # $1 - hk_verify() return code
-hk_errmsg()
-{
+hk_errmsg() {
 	case "$1" in
 	0) ;;
-	1) echo "file does not exist" ;;
-	2) echo "file has zero length" ;;
-	3) echo "file is not valid host key or not supported" ;;
-	*) echo "unknown error" ;;
+	1)
+		echo "file does not exist"
+		;;
+	2)
+		echo "file has zero length"
+		;;
+	3)
+		echo "file is not valid host key or not supported"
+		;;
+	*)
+		echo "unknown error"
+		;;
 	esac
 }
 
 # $1 - config option
 # $2 - host key file name
-hk_config()
-{
+hk_config() {
 	local x m
-	hk_verify "$2"; x=$?
+	hk_verify "$2"
+	x=$?
 	case "$x" in
-	0)	procd_append_param command -r "$2"
+	0)
+		procd_append_param command -r "$2"
 		;;
-	*)	m=$(hk_errmsg "$x")
-		logger -t "${NAME}" -p daemon.warn \
-		  "option '$1', value '$2': $m, skipping"
+	*)
+		m=$(hk_errmsg "$x")
+		logger -t "dropbear" -p daemon.warn "option '$1', value '$2': $m, skipping"
 		;;
 	esac
 }
 
 # $1 - host key file name
-hk_config__keyfile()
-{
+hk_config__keyfile() {
 	hk_config 'keyfile' "$1"
 }
 
-hk_generate_as_needed()
-{
+hk_generate_as_needed() {
 	local kdir kgen ktype tdir kcount tfile
 	kdir='/etc/dropbear'
 
@@ -74,7 +77,8 @@ hk_generate_as_needed()
 
 	[ -z "${kgen}" ] && return
 
-	tdir=$(mktemp -d); chmod 0700 "${tdir}"
+	tdir=$(mktemp -d)
+	chmod 0700 "${tdir}"
 
 	kcount=0
 	for ktype in ${kgen}; do
@@ -86,19 +90,20 @@ hk_generate_as_needed()
 			continue
 		fi
 
-		kcount=$((kcount+1))
+		kcount=$((kcount + 1))
 	done
 
 	if [ ${kcount} -ne 0 ]; then
-		mkdir -p "${kdir}"; chmod 0700 "${kdir}"; chown root "${kdir}"
+		mkdir -p "${kdir}"
+		chmod 0700 "${kdir}"
+		chown root "${kdir}"
 		mv -f "${tdir}/"* "${kdir}/"
 	fi
 
 	rm -rf "${tdir}"
 }
 
-append_ports()
-{
+append_ports() {
 	local ipaddrs="$1"
 	local port="$2"
 
@@ -112,13 +117,13 @@ append_ports()
 	done
 }
 
-validate_section_dropbear()
-{
+validate_section_dropbear() {
 	uci_load_validate dropbear dropbear "$1" "$2" \
 		'PasswordAuth:bool:1' \
 		'enable:bool:1' \
 		'Interface:string' \
 		'GatewayPorts:bool:0' \
+		'ForceCommand:string' \
 		'RootPasswordAuth:bool:1' \
 		'RootLogin:bool:1' \
 		'rsakeyfile:file' \
@@ -128,12 +133,11 @@ validate_section_dropbear()
 		'SSHKeepAlive:uinteger:300' \
 		'IdleTimeout:uinteger:0' \
 		'MaxAuthTries:uinteger:3' \
-		'RecvWindowSize:uinteger:0' \
+		'RecvWindowSize:uinteger:262144' \
 		'mdns:bool:1'
 }
 
-dropbear_instance()
-{
+dropbear_instance() {
 	local ipaddrs
 
 	[ "$2" = 0 ] || {
@@ -151,17 +155,18 @@ dropbear_instance()
 	}
 
 	[ "${enable}" = "0" ] && return 1
-	PIDCOUNT="$(( ${PIDCOUNT} + 1))"
-	local pid_file="/var/run/${NAME}.${PIDCOUNT}.pid"
+	PIDCOUNT="$((${PIDCOUNT} + 1))"
+	local pid_file="/var/run/dropbear.${PIDCOUNT}.pid"
 
 	procd_open_instance
 	procd_set_param command "$PROG" -F -P "$pid_file"
 	[ "${PasswordAuth}" -eq 0 ] && procd_append_param command -s
 	[ "${GatewayPorts}" -eq 1 ] && procd_append_param command -a
+	[ -n "${ForceCommand}" ] && procd_append_param command -c "${ForceCommand}"
 	[ "${RootPasswordAuth}" -eq 0 ] && procd_append_param command -g
 	[ "${RootLogin}" -eq 0 ] && procd_append_param command -w
 	if [ -n "${rsakeyfile}" ]; then
-		logger -t ${NAME} -p daemon.warn \
+		logger -t dropbear -p daemon.warn \
 			"option 'rsakeyfile' is considered to be deprecated and" \
 			"will be removed in future releases, use 'keyfile' instead"
 		hk_config 'rsakeyfile' "${rsakeyfile}"
@@ -172,49 +177,60 @@ dropbear_instance()
 	[ "${IdleTimeout}" -ne 0 ] && procd_append_param command -I "${IdleTimeout}"
 	[ "${SSHKeepAlive}" -ne 0 ] && procd_append_param command -K "${SSHKeepAlive}"
 	[ "${MaxAuthTries}" -ne 0 ] && procd_append_param command -T "${MaxAuthTries}"
-	[ "${RecvWindowSize}" -gt 0 -a "${RecvWindowSize}" -le 1048576 ] && \
+	[ "${RecvWindowSize}" -gt 0 ] && {
+		# NB: OpenWrt increases receive window size to increase throughput on high latency links
+		# ref: validate_section_dropbear()
+		# default receive window size is 24576 (DEFAULT_RECV_WINDOW in default_options.h)
+
+		# sysoptions.h
+		local MAX_RECV_WINDOW=10485760
+		if [ "${RecvWindowSize}" -gt ${MAX_RECV_WINDOW} ]; then
+			# separate logging is required because syslog misses dropbear's message
+			# Bad recv window '${RecvWindowSize}', using ${MAX_RECV_WINDOW}
+			# it's probably dropbear issue but we should handle this and notify user
+			logger -s -t "dropbear" -p daemon.warn \
+				"Option 'RecvWindowSize' is too high (${RecvWindowSize}), limiting to ${MAX_RECV_WINDOW}"
+			RecvWindowSize=${MAX_RECV_WINDOW}
+		fi
 		procd_append_param command -W "${RecvWindowSize}"
+	}
 	[ "${mdns}" -ne 0 ] && procd_add_mdns "ssh" "tcp" "$Port" "daemon=dropbear"
 	procd_set_param respawn
 	procd_close_instance
 }
 
-load_interfaces()
-{
+load_interfaces() {
 	config_get interface "$1" Interface
 	config_get enable "$1" enable 1
 
 	[ "${enable}" = "1" ] && interfaces=" ${interface} ${interfaces}"
 }
 
-boot()
-{
+boot() {
 	BOOT=1
 	start "$@"
 }
 
-start_service()
-{
+start_service() {
 	hk_generate_as_needed
 
 	. /lib/functions.sh
 	. /lib/functions/network.sh
 
-	config_load "${NAME}"
+	config_load "dropbear"
 	config_foreach validate_section_dropbear dropbear dropbear_instance
 }
 
-service_triggers()
-{
+service_triggers() {
 	local interfaces
 
 	procd_add_config_trigger "config.change" "dropbear" /etc/init.d/dropbear reload
 
-	config_load "${NAME}"
+	config_load "dropbear"
 	config_foreach load_interfaces dropbear
 
 	[ -n "${interfaces}" ] && {
-		for n in $interfaces ; do
+		for n in $interfaces; do
 			procd_add_interface_trigger "interface.*" $n /etc/init.d/dropbear reload
 		done
 	}
@@ -227,16 +243,14 @@ shutdown() {
 	killall dropbear
 }
 
-killclients()
-{
+killclients() {
 	local ignore=''
 	local server
 	local pid
 
 	# if this script is run from inside a client session, then ignore that session
 	pid="$$"
-	while [ "${pid}" -ne 0 ]
-	 do
+	while [ "${pid}" -ne 0 ]; do
 		# get parent process id
 		pid=$(cut -d ' ' -f 4 "/proc/${pid}/stat")
 		[ "${pid}" -eq 0 ] && break
@@ -249,15 +263,13 @@ killclients()
 	done
 
 	# get all server pids that should be ignored
-	for server in $(cat /var/run/${NAME}.*.pid)
-	 do
+	for server in $(cat /var/run/dropbear.*.pid); do
 		append ignore "${server}"
 	done
 
 	# get all running pids and kill client connections
 	local skip
-	for pid in $(pidof "${NAME}")
-	 do
+	for pid in $(pidof "dropbear"); do
 		# check if correct program, otherwise process next pid
 		grep -F -q -e "${PROG}" "/proc/${pid}/cmdline" || {
 			continue
@@ -265,10 +277,8 @@ killclients()
 
 		# check if pid should be ignored (servers, ourself)
 		skip=0
-		for server in ${ignore}
-		 do
-			if [ "${pid}" = "${server}" ]
-			 then
+		for server in ${ignore}; do
+			if [ "${pid}" = "${server}" ]; then
 				skip=1
 				break
 			fi
diff --git a/package/network/services/uhttpd/files/uhttpd.init b/package/network/services/uhttpd/files/uhttpd.init
--- a/package/network/services/uhttpd/files/uhttpd.init
+++ b/package/network/services/uhttpd/files/uhttpd.init
@@ -33,32 +33,41 @@ append_bool() {
 
 generate_keys() {
 	local cfg="$1"
-	local key="$2"
-	local crt="$3"
-	local days bits country state location organization commonname
+	local days bits country state location organization commonname key_type ec_curve
 
-	config_get days       "$cfg" days
-	config_get bits       "$cfg" bits
-	config_get country    "$cfg" country
-	config_get state      "$cfg" state
-	config_get location   "$cfg" location
+	config_get days "$cfg" days "90"
+	config_get bits "$cfg" bits "2048"
+	config_get country "$cfg" country "ZZ"
+	config_get state "$cfg" state "Somewhere"
+	config_get location "$cfg" location "Unknown"
 	config_get organization "$cfg" organization
-	config_get commonname "$cfg" commonname
-	config_get key_type   "$cfg" key_type
-	config_get ec_curve   "$cfg" ec_curve
+	config_get commonname "$cfg" commonname "OpenWrt"
+	config_get key_type "$cfg" key_type "ec"
+	config_get ec_curve "$cfg" ec_curve "P-256"
 
 	# Prefer px5g for certificate generation (existence evaluated last)
 	local GENKEY_CMD=""
-	local KEY_OPTS="rsa:${bits:-2048}"
+	local KEY_OPTS=""
+	local EXTRA_OPTS=""
 	local UNIQUEID=$(dd if=/dev/urandom bs=1 count=4 | hexdump -e '1/1 "%02x"')
-	[ "$key_type" = "ec" ] && KEY_OPTS="ec -pkeyopt ec_paramgen_curve:${ec_curve:-P-256}"
-	[ -x "$OPENSSL_BIN" ] && GENKEY_CMD="$OPENSSL_BIN req -x509 -sha256 -outform der -nodes"
-	[ -x "$PX5G_BIN" ] && GENKEY_CMD="$PX5G_BIN selfsigned -der"
+
+	if [ -x "$OPENSSL_BIN" ]; then
+		GENKEY_CMD="$OPENSSL_BIN req -x509 -sha256 -outform der -nodes"
+		[ "$key_type" = "ec" ] && KEY_OPTS="ec -pkeyopt ec_paramgen_curve:$ec_curve" || KEY_OPTS="rsa:$bits"
+		EXTRA_OPTS="-addext extendedKeyUsage=serverAuth -addext subjectAltName=DNS:$commonname"
+	elif [ -x "$PX5G_BIN" ]; then
+		GENKEY_CMD="$PX5G_BIN selfsigned -der"
+		[ "$key_type" = "ec" ] && KEY_OPTS="ec:$ec_curve" || KEY_OPTS="rsa:$bits"
+	fi
+
 	[ -n "$GENKEY_CMD" ] && {
 		$GENKEY_CMD \
-			-days ${days:-730} -newkey ${KEY_OPTS} -keyout "${UHTTPD_KEY}.new" -out "${UHTTPD_CERT}.new" \
-			-subj /C="${country:-ZZ}"/ST="${state:-Somewhere}"/L="${location:-Unknown}"/O="${organization:-OpenWrt$UNIQUEID}"/CN="${commonname:-OpenWrt}"
+			-days "$days" -newkey ${KEY_OPTS} -keyout "${UHTTPD_KEY}.new" -out "${UHTTPD_CERT}.new" \
+			-subj /C="$country"/ST="$state"/L="$location"/O="${organization:-OpenWrt$UNIQUEID}"/CN="$commonname" \
+			$EXTRA_OPTS
+
 		sync
+		chmod 600 "${UHTTPD_KEY}.new"
 		mv "${UHTTPD_KEY}.new" "${UHTTPD_KEY}"
 		mv "${UHTTPD_CERT}.new" "${UHTTPD_CERT}"
 	}
@@ -91,18 +100,30 @@ append_lua_prefix() {
 	fi
 }
 
-start_instance()
-{
+append_ucode_prefix() {
+	local v="$1"
+	local prefix="${v%%=*}"
+	local handler="${v#*=}"
+
+	if [ "$prefix" != "$handler" ] && [ -n "$prefix" ] && [ -f "$handler" ]; then
+		procd_append_param command -o "$prefix" -O "$handler"
+	else
+		echo "Skipping invalid ucode prefix \"$v\"" >&2
+	fi
+}
+
+start_instance() {
 	UHTTPD_CERT=""
 	UHTTPD_KEY=""
 
 	local cfg="$1"
 	local realm="$(uci_get system.@system[0].hostname)"
-	local listen http https interpreter indexes path handler httpdconf haveauth
+	local listen http https interpreter indexes path handler
+	local httpdconf haveauth=0
 	local enabled
 
 	config_get_bool enabled "$cfg" 'enabled' 1
-	[ $enabled -gt 0 ] || return
+	[ "$enabled" -gt 0 ] || return
 
 	procd_open_instance
 	procd_set_param respawn
@@ -113,10 +134,10 @@ start_instance()
 	if [ -z "$config" ]; then
 		mkdir -p /var/etc/uhttpd
 		httpdconf="/var/etc/uhttpd/httpd.${cfg}.conf"
-		rm -f ${httpdconf}
+		rm -f "${httpdconf}"
 		config_list_foreach "$cfg" httpauth create_httpauth
 		if [ "$haveauth" = "1" ]; then
-			procd_append_param command -c ${httpdconf}
+			procd_append_param command -c "${httpdconf}"
 			[ -r /etc/httpd.conf ] && cat /etc/httpd.conf >>/var/etc/uhttpd/httpd.${cfg}.conf
 		fi
 	fi
@@ -142,6 +163,9 @@ start_instance()
 		append_arg "$cfg" ubus_socket "-U"
 		append_bool "$cfg" ubus_cors "-X" 0
 	}
+	[ -f /usr/lib/uhttpd_ucode.so ] && {
+		config_list_foreach "$cfg" ucode_prefix append_ucode_prefix
+	}
 	append_arg "$cfg" script_timeout "-t"
 	append_arg "$cfg" network_timeout "-T"
 	append_arg "$cfg" http_keepalive "-k"
@@ -157,12 +181,12 @@ start_instance()
 
 	config_get alias_list "$cfg" alias
 	for alias in $alias_list; do
-		 procd_append_param command -y "$alias"
+		procd_append_param command -y "$alias"
 	done
 
 	config_get http "$cfg" listen_http
 	for listen in $http; do
-		 procd_append_param command -p "$listen"
+		procd_append_param command -p "$listen"
 	done
 
 	config_get interpreter "$cfg" interpreter
@@ -176,8 +200,8 @@ start_instance()
 	done
 
 	config_get https "$cfg" listen_https
-	config_get UHTTPD_KEY  "$cfg" key  /etc/uhttpd.key
-	config_get UHTTPD_CERT "$cfg" cert /etc/uhttpd.crt
+	config_get UHTTPD_KEY "$cfg" key /etc/ssl/uhttpd.key
+	config_get UHTTPD_CERT "$cfg" cert /etc/ssl/uhttpd.crt
 
 	[ -f /lib/libustream-ssl.so ] && [ -n "$https" ] && {
 		[ -s "$UHTTPD_CERT" -a -s "$UHTTPD_KEY" ] || {
@@ -186,7 +210,10 @@ start_instance()
 
 		[ -f "$UHTTPD_CERT" -a -f "$UHTTPD_KEY" ] && {
 			append_arg "$cfg" cert "-C"
-			append_arg "$cfg" key  "-K"
+			append_arg "$cfg" key "-K"
+
+			procd_append_param file "$UHTTPD_CERT"
+			procd_append_param file "$UHTTPD_KEY"
 
 			for listen in $https; do
 				procd_append_param command -s "$listen"
@@ -196,16 +223,88 @@ start_instance()
 		append_bool "$cfg" redirect_https "-q" 0
 	}
 
-	for file in /etc/uhttpd/*.json; do
+	config_get json_script "$cfg" json_script
+	for file in $json_script; do
 		[ -s "$file" ] && procd_append_param command -H "$file"
 	done
 
 	procd_close_instance
 }
 
-service_triggers()
-{
+uhttpd_interfaces() {
+	local cfg="$1"
+	local http https listen ips
+
+	config_get http "$cfg" listen_http
+	config_get https "$cfg" listen_https
+	for listen in $http $https; do
+		case "$listen" in
+		"" | "0.0.0.0:"* | "[::]:"*)
+			continue
+			;;
+		*.*.*.*:*)
+			ips="$ips ${listen%%:*}
+"
+			;;
+		\[*\]:*)
+			listen="${listen#[}"
+			ips="$ips ${listen%%]:*}
+"
+			;;
+		esac
+	done
+
+	echo "$ips" | tr ' ' '\n' | grep -v '^$' | sort -u
+}
+
+resolve_iface() {
+	local cfg="$1"
+	local testip="$2"
+	local ip ip6addrs ipaddrs
+
+	config_get ipaddrs "$cfg" ipaddr
+	config_get ip6addrs "$cfg" ip6addr
+
+	for ip in $ipaddrs $ip6addrs; do
+		[ "${ip%%/*}" = "$testip" ] && echo "$cfg"
+	done
+}
+
+get_interface_by_ip() {
+	config_foreach resolve_iface interface "$@"
+}
+
+service_triggers() {
+	local iface ifaces all=0
+
 	procd_add_reload_trigger "uhttpd"
+	procd_add_raw_trigger acme.renew 5000 /etc/init.d/uhttpd reload
+
+	config_load uhttpd
+	local ips=$(config_foreach uhttpd_interfaces uhttpd)
+
+	if [ -z "$ips" ]; then
+		procd_add_raw_trigger "interface.*.up" 1000 /etc/init.d/uhttpd start
+		return 0
+	fi
+
+	config_load network
+	for ip in $ips; do
+		iface="$(get_interface_by_ip "$ip")"
+		if [ -z "$iface" ]; then
+			all=1
+			break
+		fi
+		ifaces="$ifaces $iface"
+	done
+
+	if [ "$all" = "1" ]; then
+		procd_add_raw_trigger "interface.*.up" 1000 /etc/init.d/uhttpd start
+	else
+		for iface in $(echo $ifaces | tr ' ' '\n' | sort -u); do
+			procd_add_raw_trigger "interface.$iface.up" 1000 /etc/init.d/uhttpd start
+		done
+	fi
 }
 
 start_service() {
